"""Модели SDK для группы `gpon`."""

from ecstasy_sdk.models.schemas import (
    AddEnd3ToHouseOLTState,
    BuildingAddress,
    CommonCustomerSerializer,
    CommonSubscriberConnectionSerializer,
    CreateTechData,
    CustomerDetail,
    End3,
    End3TechCapability,
    ErrorDetailResponse,
    OLTSubscriber,
    PaginatedSubscriberConnectionListResponse,
    PaginatedTechDataListResponse,
    StructuresHouseOLTState,
    SubscriberData,
    TechCapability,
    UpdateHouseOLTState,
    UpdateRetrieveOLTState,
    UpdateSubscriberData,
    ViewHouseBTechData,
    ViewOLTStatesTechData,
)

__all__ = [
    "AddEnd3ToHouseOLTState",
    "BuildingAddress",
    "CommonCustomerSerializer",
    "CommonSubscriberConnectionSerializer",
    "CreateTechData",
    "CustomerDetail",
    "End3",
    "End3TechCapability",
    "ErrorDetailResponse",
    "OLTSubscriber",
    "PaginatedSubscriberConnectionListResponse",
    "PaginatedTechDataListResponse",
    "StructuresHouseOLTState",
    "SubscriberData",
    "TechCapability",
    "UpdateHouseOLTState",
    "UpdateRetrieveOLTState",
    "UpdateSubscriberData",
    "ViewHouseBTechData",
    "ViewOLTStatesTechData",
]
